# These settings and configurations are consistent across different environments.
# Inconsistent and secret settings and configurations should be placed in the .env files,
# using the .env.example files.

# OpenAPI information.
[openapi]
title = "URL Shortener API"
version = "1.0.0"
description = """A URL shortener web service built with FastAPI."""

[openapi.contact]
name = "Rental House API Support Team"
email = "alihezarpisheh@outlook.com"

[openapi.license]
name = "MIT License"
url = "https://opensource.org/licenses/MIT"

[[openapi.tags]]
name = "URL-Shortener"
description = "Operations related to user management, including registration, authentication, and profile management."

[[openapi.tags]]
name = "Health Check"
description = "A simple endpoint to check if the API is up and running."

# Logging configuration.
[logging]
version = 1
disable_existing_loggers = false

[logging.formatters.coloredFormatter]
"()" = "coloredlogs.ColoredFormatter"
format = "%(asctime)s - %(levelname)s - %(name)s - %(relativepath)s:%(lineno)d - %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.formatters.fileFormatter]
format = "%(asctime)s - %(levelname)s - %(name)s - %(relativepath)s:%(lineno)d - %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.handlers.consoleHandler]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "coloredFormatter"

[logging.handlers.fileHandler]
level = "INFO"
class = "logging.handlers.RotatingFileHandler"
filename = "logs/url-shortener.log"
maxBytes = 1048576   # 1 MB
backupCount = 10
formatter = "fileFormatter"

[logging.loggers.development]
level = "DEBUG"
handlers = ["consoleHandler", "fileHandler"]
propagate = true

[logging.loggers.production]
level = "INFO"
handlers = ["fileHandler"]
propagate = true

[logging.loggers.uvicorn]
level = "DEBUG"
handlers = ["consoleHandler", "fileHandler"]
propagate = true

[logging.loggers.uvicorn.error]
level = "DEBUG"
handlers = ["consoleHandler", "fileHandler"]
propagate = true

[logging.loggers.uvicorn.access]
level = "DEBUG"
handlers = ["consoleHandler", "fileHandler"]
propagate = true
